vich_uploader:
    db_driver: orm

    mappings:
        new_actu:
            uri_prefix: /uploadimg/images
            upload_destination: '%kernel.project_dir%/public/uploadimg/images'
            #namer: Vich\UploaderBundle\Naming\UniqiNamer
