vich_uploader:
    db_driver: orm

    mappings:
        new_actu:
            uri_prefix: /uploadimg/images
            upload_destination: '%kernel.project_dir%/public/uploadimg/images'
            #namer: Vich\UploaderBundle\Naming\UniqiNamer
        user_pp:
            uri_prefix: /uploadimg/images
            upload_destination: '%kernel.project_dir%/public/uploadimg/images'
            #namer: Vich\UploaderBundle\Naming\UniqiNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
